In [1]:
import numpy as np
from IPython.display import Image
from IPython.core.display import HTML 

# Numpy is a library about numerical computing and the gateway to Python Data Science.


In [2]:

Image(url="stack.png", width=600, height=600)

## Python has lists which can be treated by python like arrays. 


In [3]:
number_list = [1,2,3,4]
grocery_list = ['banana','grape','apple']
float_list = [1.0, 2.0, 3.14, 4.0]
lists_of_other_things = [{'a','set'}, ['list','inside','list']]
matrix = [[1,2,3,4],
          [2,3,4,5],
          [3,4,5,6]]  # just a list of lists

## But here is why we need something better.   
### Lets start with making a list of list with range.

In [4]:
matrix = []
inner = []
for j in range(50):
    for i in range(10):
        inner.append(i+j*10)
    matrix.append(inner)
    inner = []
matrix

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
 [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
 [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
 [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
 [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
 [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
 [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
 [90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
 [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
 [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
 [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
 [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
 [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
 [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
 [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
 [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
 [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
 [190, 191, 192, 193, 194, 195, 196, 197, 198, 199],
 [200, 201, 202, 203, 204, 205, 206, 207, 208, 209

In [5]:
# the same structure with numpy arrays made in one line.
np_array = np.arange(500).reshape(50,10)
np_array

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [6]:
def add10(matrix):
    for count_x,x in enumerate(matrix):
        for count_y,y in enumerate(x):
            matrix[count_x][count_y]+=10
    return matrix

%timeit add10(matrix)

89.3 µs ± 2.98 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
%timeit np_array+10

1.21 µs ± 11 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### 70x speedup.
Note: This is just adding.  There are operations or combinations of operations which can get you 100x or 1000x speedup.  Lets put that into perspective.  If you have a lot of data to work on and this operation takes a month, a 30x speed up would reduce that to a day.  a 70x speedup would reduce that to 10 hours or so.  So you could make changes during the day.  let this run all night and come back in the morning and it would be done.  You can make a few mistakes and still be done in a week or so.  Fast iteration is key in data science.  Numpy is a significant tool to make that possible.

### You will have to be specific when you are doing matrix multiplication as to which operation you are looking to do.

In [8]:
import numpy as np
np_a = np.arange(10).reshape(1,10)
print(np_a)
np_b = np.arange(10).reshape(10,1)
print(np_b)


[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


### Did you want this?  (notice the order of the arguments stays the same)

In [9]:
np.multiply(np_a, np_b) #element wise

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

### or this

In [10]:
np.dot(np_a,np_b) # linear algebra matrix multiplication

array([[285]])

## This is a breakdown of the Numpy Header. 
### Data pointer 
The memory address of the first
byte in the array.

###  Data type description 
The kind of elements contained
in the array, for example floating point
numbers or integers.

### Shape 
The shape of the array, for example (10,
10) for a ten-by-ten array, or (5, 5, 5) for a
block of data describing a mesh grid of x-, yand
z-coordinates.

### Strides
The number of bytes to skip in memory to
proceed to the next element. For a (10, 10)
array of bytes, for example, the strides may be
(10, 1), in other words: proceed one byte to
get to the next column and ten bytes to locate
the next row.

### Flags 
Which define whether memory layout is
C- or Fortran-contiguous1
, and so forth.

data from https://arxiv.org/pdf/1102.1523.pdf

### And header helps figure out how to split that data up.

## You may need to modify the flags to change elements in the array  (Depending on how it's created)

In [11]:
a = np.arange(6).reshape(2,3)
for x in np.nditer(a[:,2], op_flags=['readwrite']):
    x[...] = 2 * x
print(a)

[[ 0  1  4]
 [ 3  4 10]]


### Python has lots of space for numbers that you rarely need.  So you can modify the size of the data before you do calculations.  The computer can operate on 32 bits faster than it can on 64 bits.  

#### With 8 bits you can hold numbers from 0-255, 
#### with 16 bits you can hold numbers from 0-65535, 
#### with 32 bits you can hold numbers from 0-4294967295
#### with 64 bits you can hold numbers from 0-18446744073709551616
##### (all these are unsigned integers.)

### So how many bits do you need to hold a number representing:
#### A persons age?  (Do people live to be 4 million?)
#### People living in a major city?
#### Cars manufactured in a year by a company?

In [12]:
#if you want to find out how many bits data has use:
a.dtype

dtype('int64')

### So this ndarray can hold numbers going to 18446744073709551616.  And it using the space for it even though the number is small.  But you can change the datatype using astype()

In [13]:
a = a.astype(np.int8)

In [14]:
a.dtype

dtype('int8')

In [15]:
a

array([[ 0,  1,  4],
       [ 3,  4, 10]], dtype=int8)

## Where is a replacement for an if statement with certain conditions.

In [16]:
#This sets all values less than or equal to five to 0 and leaves the rest alone.
np.where(a > 5, a, 0)

array([[ 0,  0,  0],
       [ 0,  0, 10]], dtype=int8)

When functions in Numpy operate on one value at a time there called Ufuncs.  where(), sum(), min(), max() ar a few.

In [20]:
print(a)
a.sum()

[[ 0  1  4]
 [ 3  4 10]]


22

## The reason for the speed improvement is the data layout.

(numbers are actually in binary but this is just an easier version for people to read)

A list is structured like this:
    [pointer to the memory address of 5, pointer to the memory address of 1, pointer to the memory address of 3, ...]
    
    integer00000001                                       integer00000001
    
    
                integer00000003                                          integer00000005
        integer00000004


The structure is only like this for 1d lists.  For 2d lists the first list would point to another set of lists which would then point to the values. 

A NumPy array data is structured like this: 

### NumpyHeaderHere:0000000100000002000000030000000400000005

This structure holds true for 1d, 2d, 3d... all the way to ND data.  And that's a reason it is called an ndarray.

# Thanks for taking the time to learn about Numpy arrays.  Start using them and hurry.